custom:
  contact:
    email: sebastien.burckhardt+dev@hoenheimsports.fr
spring:
  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  docker:
    compose:
      file: ./backend/docker-compose-support/docker-compose-contact.yml
      lifecycle-management: start-and-stop