spring:
  docker:
    compose:
      file: ./backend/docker-compose-support/docker-compose-facebook.yml
      lifecycle-management: start-and-stop
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8079/realms/ashs
facebook:
  api:
    url: ${FACEBOOK_API_URI}
    client-id: ${FACEBOOK_CLIENT_ID}
    client-secret: ${FACEBOOK_CLIENT_SECRET}