spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:4200"
            allowed-methods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowed-headers:
              - "Authorization"
              - "Content-Type"
              - "Accept"
            allow-credentials: true

custom:
  cors:
    allowed-origins:
      - "http://localhost:4200"
# in production
#      x-forwarded:
#        enabled: true


