spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "https://frontend"
              - "https://admin"
              - "https://www.hoenheimsports.fr"
              - "https://admin.hoenheimsports.fr"
            allowed-methods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowed-headers:
              - "Authorization"
              - "Content-Type"
              - "Accept"
            allow-credentials: true

custom:
  cors:
    allowed-origins:
      - "https://frontend"
      - "https://admin"