spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:4200"
              - "http://localhost:8080"
              - "http://localhost:8081"
              - "http://localhost:8082"
              - "http://localhost:8083"