spring:
  docker:
    compose:
      file: ./backend/docker-compose-support/docker-compose-training.yml
      lifecycle-management: start-and-stop
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8079/realms/ashs


