spring:
  flyway:
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SECURITY_OAUTH2_JWT_ISSUER_URI}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URI}